# Generated by Django 5.0.7 on 2024-07-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_article_titl_articles_article_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Articles2',
        ),
    ]
