# Generated by Django 5.0.7 on 2024-07-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_articles_articles2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles2',
            new_name='Article',
        ),
    ]
