# Generated by Django 5.0.7 on 2024-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_articles2_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_cover',
            field=models.ImageField(blank=True, null=True, upload_to='article_covers/'),
        ),
    ]
