# Generated by Django 5.0.7 on 2024-07-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_article_date_created_alter_article_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_cover_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
